Fix/36 too many results
imimap/imimap21 pull request #251
Opened 2022-02-08 08:00 UTC by LiFaytheGoblin

creates an endpoint to count possible amount of results

2022-02-10 11:19 UTC, LiFaytheGoblin commented
es gibt gerade ein problem. 
![image](https://user-images.githubusercontent.com/5471273/153396743-09dacdb0-33c3-4fd2-a092-09163a495a0d.png)
es bleibt immer beim ersten resultat von wieviele internships man schon gesehen hatte (7) stecken, auch wenn man mittlerweile schon 12 gesehen hat weil man ja die ergebnisse von davor angeschaut hat.

2022-02-10 11:49 UTC, LiFaytheGoblin commented
new problem: 

![image](https://user-images.githubusercontent.com/5471273/153402680-54d895c9-17e3-43f3-ba96-45f59ea757a9.png)


it should not show the modal in the case that one has already seen 12 internships. in that case it should just show the list. i don't get why this won't work

![image](https://user-images.githubusercontent.com/5471273/153403050-e61d7194-360d-4349-b533-9d6313cf4e22.png)

clearly the amount of seen internships is 12?!

2022-02-10 12:00 UTC, LiFaytheGoblin commented
Problem nr 2: 

ein user hat bereits 9 (eine zahl >6) ergebnisse gesehen, und klickt auf suchen. Dann kommt das:

![image](https://user-images.githubusercontent.com/5471273/153404649-eca82cd1-ccb9-411e-a1e8-cb879f33e979.png)

2022-02-10 12:07 UTC, LiFaytheGoblin commented
warum sagt es ich hätte bereits 2 gesehen?

![image](https://user-images.githubusercontent.com/5471273/153405674-158ea569-dfc0-478d-ba2e-ef77ca0ab3c6.png)

2022-02-12 17:02 UTC, JuliaZamaitat commented
@LiFaytheGoblin Sind die Probleme behoben, da du review requested hast, oder hast du Review auf die Fragen requested?

2022-02-14 09:33 UTC, LiFaytheGoblin commented
> @LiFaytheGoblin Sind die Probleme behoben, da du review requested hast, oder hast du Review auf die Fragen requested?

@JuliaZamaitat Ich hab die Probleme behoben oben und wollte auf das Resultat gern einen Review haben :)

2022-02-14 19:58 UTC, Kaes3kuch3n requested changes

2022-02-14 19:58 UTC, Kaes3kuch3n commented on client/src/components/search/TooManyResults.vue
> +  },
Kannst Du hier das Event noch emitten? [Siehe Vue-Docs :)](https://vuejs.org/guide/components/events.html#declaring-emitted-events)

2022-02-14 19:58 UTC, Kaes3kuch3n commented on server/src/routes/internship.ts
> +const idRegEx = /[0-91-f]{24}/;
```suggestion
const idRegEx = /[0-9a-f]{24}/;
```
Ich glaube, dass sollte eigentlich ne Hex-Regex sein 😅

2022-02-14 19:58 UTC, Kaes3kuch3n commented on server/src/controllers/internship.ts
> +  res.json(internships[0].totalCount[0].count);
Hier gibt's nen Error, wenn die Suche keine Ergebnisse zurückgibt, weil totalCount dann ne Length von 0 hat

2022-02-15 12:56 UTC, merged