add star to required field
imimap/imimap21 pull request #256
Opened 2022-02-14 13:49 UTC by LiFaytheGoblin

adds css class "required" which adds a red star after the element

adds this css class to the required fields in internship and company creation (which is actually only the company name, according to the mongoose model)

![image](https://user-images.githubusercontent.com/5471273/153876293-ceae0e70-4a1d-4a25-9630-535690335a12.png)

fixes #212

2022-02-14 14:02 UTC, LiFaytheGoblin commented
however, if saving just with a company name we receive a 500

Internship validation failed: supervisor.emailAddress: Expected a string but received a null, supervisor: Validation failed: emailAddress: Expected a string but received a null

2022-02-14 14:18 UTC, LiFaytheGoblin commented
experimenting with fixing the above issue at [fix/212-fix-internship-creation-controller](https://github.com/imimap/imimap21/tree/fix/212-fix-internship-creation-controller)

2022-02-15 15:09 UTC, LiFaytheGoblin commented
so far, there's still a problem when I create a new internship, then add a new company and then hit save internship:

![image](https://user-images.githubusercontent.com/5471273/154090039-f72353d2-b312-439f-b135-ced4af9a9635.png)

2022-02-15 15:49 UTC, LiFaytheGoblin commented
there's still a problem when I edit an internship and type in a new prop value in the form and click save:
![image](https://user-images.githubusercontent.com/5471273/154097661-009dd53f-5a8b-4a03-aada-9477f28f4038.png)

2022-02-18 13:56 UTC, LiFaytheGoblin commented
New problem:
When I patch an internship sending new info, the data is not updated in the db apparently

2022-02-18 14:00 UTC, LiFaytheGoblin commented
Problem: When I click on "bearbeiten" for my newly created internship it just shows nothing.

2022-02-18 15:43 UTC, LiFaytheGoblin commented
New problem: When I hit save when editing an internship I get 
`[Vue warn]: Attempting to mutate public property "$data". Properties starting with $ are reserved and readonly. `

`Fehler beim Speichern des Praktikums [ERROR: proxy set handler returned false for property '"$data"'] `

Edit: Fixed in [511ce90](https://github.com/imimap/imimap21/pull/256/commits/511ce90dd4c7f20b46713bcd521061ce53fe91aa)

2022-02-19 11:34 UTC, JuliaZamaitat requested changes
Beim Editieren des Praktikums werden die neu eingetragenen Sachen immer noch nicht gespeichert, obwohl die Meldung kommt, dass es gespeichert wurde. 

Zudem würde ich den Knopf "Weiteres Teilpraktikum eintragen" umbenennen in "Praktikum eintragen" solange noch keins eingetragen ist, und erst wenn es schon ein Teilpraktikum gibt den Text verwenden.

2022-02-20 10:15 UTC, LiFaytheGoblin commented
@JuliaZamaitat welche felder versuchst du zu editieren?

2022-02-20 14:44 UTC, JuliaZamaitat commented
@LiFaytheGoblin Ok dann machen wir es in dem anderen Issue! Ich hatte auch so Sachen wie Startdate versucht, Salary etc aber auch, es hat bisher nichts geupdatet.

2022-02-20 14:44 UTC, JuliaZamaitat approved these changes

2022-02-23 15:00 UTC, Kaes3kuch3n approved these changes

2022-02-23 15:00 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +                   :placeholder="startDate ?? false"/>
Würde ich einfach weglassen, weil es ja nicht vom Date-Input unterstützt wird

2022-02-23 15:00 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +                   :placeholder="endDate ?? false"/>
s.o.

2022-02-23 15:00 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +      endDate: null as unknown as string,
```suggestion
      startDate: null as string | null,
      endDate: null as string | null,
```

2022-02-25 13:48 UTC, LiFaytheGoblin commented on client/src/components/internship/EditInternship.vue
> +                   :placeholder="startDate ?? false"/>
Hab ich gemacht weil in vue 2 wenn ein placeholder false ist der einfach weggelassen wird. Hab gerade erst gesehen dass sich das bei vue3 geändert hat:

https://stackoverflow.com/questions/42874314/vuejs-conditionally-add-an-attribute-for-an-element/64598898#64598898

jetzt sollte der Wert null sein, wenn der placeholder weggelassen werden soll. also daher muss ich das nochmal überarbeiten

2022-03-05 09:39 UTC, merged