display current values for start and end date
imimap/imimap21 pull request #257
Opened 2022-02-14 13:51 UTC by LiFaytheGoblin

see #255

2022-02-14 20:47 UTC, Kaes3kuch3n requested changes

2022-02-14 20:47 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +            <label for="startDate">Startdatum (currently: {{startDate}})</label>
Magst Du das hier auch gleich localizen? Also das "currently" :D

2022-02-14 20:47 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +            <label for="endDate">Enddatum (currently: {{endDate}})</label>
Und hier auch?

2022-02-15 10:10 UTC, LiFaytheGoblin commented on client/src/components/internship/EditInternship.vue
> +            <label for="startDate">Startdatum (currently: {{startDate}})</label>
true! hab ich total vergessen xD

2022-02-15 10:10 UTC, LiFaytheGoblin commented on client/src/components/internship/EditInternship.vue
> +            <label for="endDate">Enddatum (currently: {{endDate}})</label>
danke!

2022-02-15 11:05 UTC, merged