Fix/40 make postponement request
imimap/imimap21 pull request #266
Opened 2022-02-18 17:53 UTC by LiFaytheGoblin

fixes #40

2022-02-19 11:41 UTC, JuliaZamaitat requested changes
<img width="726" alt="image" src="https://user-images.githubusercontent.com/33123853/154799205-5aadeab3-ca1c-41bd-94f8-6a8d3147f784.png">

Docker meckert da noch rum, obwohl die Übersetzung im Browser zu funktionieren scheint.

2. 
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/33123853/154799252-9b1d09d4-8242-43bc-87aa-4a1f0e30ec9b.png">

Wenn abgelehnt wurde, erscheint es noch als extra Zeile statt das "requested" zu ersetzen. Angenommene Postponents werden gar nicht angezeigt.

2022-02-20 10:22 UTC, LiFaytheGoblin commented
@JuliaZamaitat 

1. Das hatte ich auch. Hat aber funktioniert nachdem ich neu gebuilded hatte. Evtl hilft `docker container prune`. Könntest du es nochmal versuchen?

2. Danke für den Reminder! Wärs ok wenn ich das separat löse? https://github.com/imimap/imimap21/issues/39

2022-02-20 14:42 UTC, JuliaZamaitat commented
@LiFaytheGoblin 

1. Ja damit scheint es weg zu sein, danke :)
2. Klar!

2022-02-20 14:42 UTC, JuliaZamaitat approved these changes

2022-02-23 15:04 UTC, Kaes3kuch3n approved these changes

2022-02-25 13:45 UTC, merged