Issue 233: Admin Quick Actions
imimap/imimap21 pull request #275
Opened 2022-02-26 20:39 UTC by Kaes3kuch3n

Fixes #233

2022-03-05 08:22 UTC, LiFaytheGoblin commented
![image](https://user-images.githubusercontent.com/5471273/156875126-1433b1dd-15d7-463a-bd2b-8333552971fd.png)

2022-03-05 08:36 UTC, LiFaytheGoblin commented on client/src/components/admin/UsersList.vue
> +      // TODO: Maybe use the updated internship returned by the API for updating the frontend.
gibts dafür schon einen issue?

2022-03-05 09:22 UTC, LiFaytheGoblin requested changes
Hab den Code so reviewt, konnte aber leider nicht testen da der Client bei mir nicht läuft. Keine Ahnung was da gerade los ist :(
jetzt läuft nicht mal mehr die db

![image](https://user-images.githubusercontent.com/5471273/156877290-ac2d8610-aaa8-4936-a419-0b28b2852ae2.png)

2022-03-05 09:22 UTC, LiFaytheGoblin commented on client/src/components/admin/modals/EditInternshipPartModal.vue
> +            <label for="supervisorFirstName" class="form-label">Supervisor</label>
Ist das jetzt der first name oder der full name?

2022-03-05 09:22 UTC, LiFaytheGoblin commented on client/src/components/admin/modals/EditInternshipPartModal.vue
> +    getSupervisorFirstName(): string {
scheint nicht benutzt zu werden

2022-03-05 09:22 UTC, LiFaytheGoblin commented on client/src/components/admin/modals/EditInternshipPartModal.vue
> +    getSupervisorLastName(): string {
scheint nicht benutzt zu werden

2022-03-05 09:22 UTC, LiFaytheGoblin commented on client/src/components/admin/users-list/InternshipPart.vue
> +              internship.endDate) / 7)
ich fände es cleaner wenn getTimeDifference zu getTimeDifferenceWeeksAndDays: { weeks: Number, days: number } gerefactored würde oder so. Ist komisch dass die Funktion im Template steht. Ist aber vlt auch etwas unnötiger Aufwand also wär für mich ok wenn es so bleibt.

2022-03-05 09:22 UTC, LiFaytheGoblin commented on server/src/controllers/internship.ts
> +  } catch (e) {
geht das jetzt doch ohne den typ any zu setzen?

2022-03-05 09:22 UTC, LiFaytheGoblin commented on server/src/controllers/internship.ts
> +    if (propsObject.supervisorFullName !== undefined)
reicht hier auch `if (propsObject.supervisorFullName)`

2022-03-05 09:22 UTC, LiFaytheGoblin commented on server/src/controllers/internship.ts
> +    if (propsObject.supervisorFullName !== undefined)
auch bei den anderen undefined vergleichen. ich mein wenn's null ist ist auch doof. null braucht man nur beim patchen denk ich

2022-03-05 09:22 UTC, LiFaytheGoblin commented on server/src/helpers/userHelper.ts
> +  return await user.populate("studentProfile.internship").execPopulate();
ach so geht das xD

2022-03-05 09:22 UTC, LiFaytheGoblin commented on server/src/routes/internship.ts
> +  "/:id/approve",
mich stört noch ein bisschen dass in der url etwas anderes als nur entities stehen (also auch ein verb) aber ich wüsste gerade auch nicht wie man's anders machen könnte. höchstens vlt `?status=approve". Hm.

2022-03-07 15:00 UTC, Kaes3kuch3n commented on server/src/controllers/internship.ts
> +  } catch (e) {
Ja, im catch-Block ist das kein Problem, da der Error ja einfach weitergegeben wird. Und das vermeidet dann, das ESLint über das any meckert :D

2022-03-07 15:04 UTC, Kaes3kuch3n commented on server/src/controllers/internship.ts
> +    if (propsObject.supervisorFullName !== undefined)
Die Methode wird ja für POST und PATCH gleichermaßen verwendet, deswegen hab ich das so gebastelt. Und im Backend dürfen die Properties ja auch auf null gesetzt werden, von daher sind's gültige Werte.

2022-03-07 15:04 UTC, Kaes3kuch3n commented on server/src/helpers/userHelper.ts
> +  return await user.populate("studentProfile.internship").execPopulate();
Ja, musste auch nochmal googlen, warum das nicht funktioniert :P

2022-03-07 15:08 UTC, Kaes3kuch3n commented on server/src/routes/internship.ts
> +  "/:id/approve",
Wär ne Möglichkeit, aber dann müsste man in `updateInternship` wieder zwischen den einzelnen Requests unterscheiden und die entsprechende Action ausführen, anstatt auf Router-Ebene direkt auf die richtige Action zu verweisen. Ich find beides nicht optimal, aber das hier ein bisschen einfacher 😅 Deswegen würde ich es so lassen.

2022-03-07 15:12 UTC, Kaes3kuch3n commented on client/src/components/admin/UsersList.vue
> +      // TODO: Maybe use the updated internship returned by the API for updating the frontend.
Jetzt ja (#280) 😛

2022-03-08 08:22 UTC, LiFaytheGoblin commented on server/src/controllers/internship.ts
> +  } catch (e) {
Ohhh achso. Gute zu wissen!

2022-03-08 08:23 UTC, LiFaytheGoblin commented on server/src/controllers/internship.ts
> +    if (propsObject.supervisorFullName !== undefined)
Ok verstehe

2022-03-08 08:23 UTC, LiFaytheGoblin commented on server/src/routes/internship.ts
> +  "/:id/approve",
Ok :)

2022-03-08 08:23 UTC, LiFaytheGoblin approved these changes

2022-03-08 17:54 UTC, merged