213 calculating internship duration
imimap/imimap21 pull request #293
Opened 2022-10-20 15:49 UTC by JuliaZamaitat

closes #213 
closes #287 

- refactored EditInternship for students
- refactored EditInternshipPart for admins
- fixed calculation of weeks between internship start and end date and display it everywhere correctly

2022-10-21 07:26 UTC, JuliaZamaitat commented
closes #294

2022-10-27 11:32 UTC, Kaes3kuch3n requested changes
Ein paar kleine Anmerkungen hab ich, sieht aber alles in allem gut aus ^^

2022-10-27 11:32 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +                   :placeholder="internship.programmingLanguages?.toString().split(',').join(', ') ?? $t('internship.form.programmingLanguages')"
```suggestion
                   :placeholder="internship.programmingLanguages?.toString().replaceAll(',', ', ') ?? $t('internship.form.programmingLanguages')"
```
Find ich ein bisschen schöner, ist aber wahrscheinlich nur personal preference 😄

2022-10-27 11:32 UTC, Kaes3kuch3n commented on server/src/helpers/dateHelper.ts
> +  return Math.round((endDate.getTime() - startDate.getTime()) / (7 * 24 * 60 * 60 * 1000));
Wenn hier sowohl `startDate` als auch `endDate` inklusive sein sollen, dann müsste noch ein Tag dazuaddiert werden. Das Runden sorgt außerdem dafür, dass eine angefangene Woche ab einer Länge von 4 Tagen als ganze Woche gezählt wird. Soll das so?

2022-10-27 11:32 UTC, Kaes3kuch3n commented on client/src/components/admin/modals/EditInternshipPartModal.vue
> +<!-- eslint-disable max-len -->
Soll das hier bleiben? 🤔 Würde sonst eher `'max-len': ['error', {'code': 150}],` zu den ESLint-Rules hinzufügen, damit es zur EditorConfig passt

2022-10-27 11:32 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +<!-- eslint-disable max-len -->
Soll das hier bleiben? 🤔

2022-10-27 11:32 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +                   :placeholder="internship.operationalArea ?? $t('internship.form.operationalArea')"/>
Dadurch, dass die ganzen Inputs jetzt die eigentliche Internship Property modeln, wird die auch immer direkt geupdated, wenn man den Input ändert. Placeholder werden aber nur bei leerem Input angezeigt. Wenn jetzt die Property durch clearen des Inputs geleert wird, sollte ein Placeholder angezeigt werden, aber der wird auch gecleart, da er ja mit gemodelt wird 😅 (Gilt für alle Placeholder hier in EditInternship) Von daher könnten die dann auch einfach weg, würde ich sagen.

2022-10-27 11:32 UTC, Kaes3kuch3n commented on client/src/components/internship-module/Internship.vue
> +                {{ startDate?.toLocaleDateString() }}
Ich würde hier bei den beiden Dates als Locale noch `$i18n.locale` übergeben, damit das Datumsformat zur eingestellten Sprache der Seite passt und nicht vom System übernommen wird.

Und personal preference: Als Options noch `{day: "2-digit", month: "2-digit", year: "numeric"}`, damit das Datum immer gleich viele Ziffern hat 😄

2022-10-27 16:06 UTC, JuliaZamaitat commented on server/src/helpers/dateHelper.ts
> +  return Math.round((endDate.getTime() - startDate.getTime()) / (7 * 24 * 60 * 60 * 1000));
Ja wegen zwei Tagen machen wir bei der Anerkennung genehmigen wir wegen zwei drei Tagen trotzdem das Praktikum, deshalb sollte das kein Problem sein.

2022-10-27 16:07 UTC, JuliaZamaitat commented on server/src/helpers/dateHelper.ts
> +  return Math.round((endDate.getTime() - startDate.getTime()) / (7 * 24 * 60 * 60 * 1000));
Warum muss dann noch ein Tag addiert werden 🤔

2022-10-27 18:22 UTC, Kaes3kuch3n commented on server/src/helpers/dateHelper.ts
> +  return Math.round((endDate.getTime() - startDate.getTime()) / (7 * 24 * 60 * 60 * 1000));
Wenn ich ein Praktikum vom 05.10.22 bis zum 23.10.22 mache und die beiden Daten voneinander abziehe (23-5), kommen 18 Tage raus. Ich war aber ja sowohl am 05. als auch am 23. noch im Praktikum, also müssten es eigentlich 19 Tage sein.

2022-10-27 18:24 UTC, Kaes3kuch3n approved these changes

2022-10-28 07:17 UTC, merged