checkinf whether internship status is passed, then disabling editing ...
imimap/imimap21 pull request #300
Opened 2022-11-02 11:02 UTC by JuliaZamaitat

…of internhip.

2022-11-05 19:47 UTC, Kaes3kuch3n requested changes
Wenn wir es ordentlich machen wollen, müssten wir auch noch serverseitig den Status checken, damit auch direkte API-Requests nen Fehler zurückgeben, wenn der Status schon `PASSED` ist 🤔

2022-11-05 19:47 UTC, Kaes3kuch3n commented on client/src/components/internship-module/Internship.vue
> +        :to="{ name: 'EditInternship', params: { id: this.internship._id } }">
Ich fürchte, hier fehlt der schließende Tag und der Link-Text

2022-11-09 07:31 UTC, JuliaZamaitat commented
> Wenn wir es ordentlich machen wollen, müssten wir auch noch serverseitig den Status checken, damit auch direkte API-Requests nen Fehler zurückgeben, wenn der Status schon `PASSED` ist 🤔

done :)

2022-11-09 07:33 UTC, JuliaZamaitat commented
> Wenn wir es ordentlich machen wollen, müssten wir auch noch serverseitig den Status checken, damit auch direkte API-Requests nen Fehler zurückgeben, wenn der Status schon `PASSED` ist 🤔

done :)

2022-11-09 23:00 UTC, Kaes3kuch3n approved these changes

2022-11-09 23:01 UTC, merged