62 - Upload PDF file views
imimap/imimap21 pull request #307
Opened 2022-11-11 14:31 UTC by Kaes3kuch3n

* Moved PDF upload modal to separate component
* Added file upload functionality for all PDF types
* Added localisation support
* Added status badges for PDF files

2022-11-23 07:27 UTC, JuliaZamaitat submitted a review, later dismissed
Hey @Kaes3kuch3n, voll gut bereits, ein paar kleine Sachen noch und paar Fragen:

- Studi: Man kann auf "Hochladen" klicken, ohne ein Dokument ausgewählt zu haben, und es steht dann trotzdem "Eingereicht" da
- Admin: Beim Runterladen der Files: Name der Files: Es steht nur "Antrag (1)", alle Dateien ohne Studiinfos, die du ja eig. hinzugefügt hast?
- Localisation für Admin fehlt noch (steht im Moment **Antrag (submitted)** dort)
- Vielleicht wäre es gut, wenn ein Studi seine eingereichten Unterlagen auch anschauen könnte? Und wie kann man gegebenenfalls neue Dokumente hochladen, falls die alten unvollständig waren? 🤔 Bezieht sich auch etwas auf hier dann https://github.com/imimap/imimap21/issues/305
- Ich glaube du wolltest das automatische Generieren des Antrags auch noch in den PR rein nehmen, oder willst du das extra machen?

2022-12-01 23:47 UTC, Kaes3kuch3n commented
> * Studi: Man kann auf "Hochladen" klicken, ohne ein Dokument ausgewählt zu haben, und es steht dann trotzdem "Eingereicht" da

Das konnte ich leider nicht reproduzieren 😬 Ich hab jetzt aber den Upload-Button disabled, bis eine Datei ausgewählt wurde.

> * Admin: Beim Runterladen der Files: Name der Files: Es steht nur "Antrag (1)", alle Dateien ohne Studiinfos, die du ja eig. hinzugefügt hast?

Gefixt 👍

> * Localisation für Admin fehlt noch (steht im Moment **Antrag (submitted)** dort)

Gefixt 👍

> * Vielleicht wäre es gut, wenn ein Studi seine eingereichten Unterlagen auch anschauen könnte? Und wie kann man gegebenenfalls neue Dokumente hochladen, falls die alten unvollständig waren? 🤔 Bezieht sich auch etwas auf hier dann #305

Hab die hochgeladenen Dateien für die Studis unter dem jeweiligen PDF-Namen verlinkt. Passt das?

Ja, für's Hochladen von neuen muss #305 implementiert werden, dann funktioniert das alles. Der Upload-Button taucht bei abgelehnten PDFs schon automatisch auf mit dem Label "Neu hochladen".

> * Ich glaube du wolltest das automatische Generieren des Antrags auch noch in den PR rein nehmen, oder willst du das extra machen?

Done 👍 Danke für die Erinnerung 😄

2022-12-02 00:03 UTC, Kaes3kuch3n commented
So, und Conflicts sind jetzt auch gefixt 👍 Ready for another review 😊

2023-01-15 20:37 UTC, JuliaZamaitat requested changes
super cool, funktioniert alles super!

Nur der disabled button "hochladen" wird wieder verfügbar, wenn man irgendein Dokument mal hochgeladen hat, also hat man zb bei Antrag ein Dokument hochgeladen, ist auch bei ECTs der Button enabled obwohl dort nichts ausgewählt wurde.

2023-01-22 20:00 UTC, Kaes3kuch3n commented
> super cool, funktioniert alles super!
> 
> Nur der disabled button "hochladen" wird wieder verfügbar, wenn man irgendein Dokument mal hochgeladen hat, also hat man zb bei Antrag ein Dokument hochgeladen, ist auch bei ECTs der Button enabled obwohl dort nichts ausgewählt wurde.

Ist gefixt 👍

2023-01-23 14:16 UTC, JuliaZamaitat approved these changes

2023-01-23 14:16 UTC, merged