297 edit company details
imimap/imimap21 pull request #310
Opened 2022-11-30 18:23 UTC by JuliaZamaitat

closes #297

2022-11-30 18:24 UTC, JuliaZamaitat commented on server/src/controllers/company.ts
> +  // if (!user.isAdmin ) return next(new Forbidden("Only admins may edit companies"));
@Kaes3kuch3n Brauchen wir noch irgendwo die Einschränkung? Ich glaub nicht, oder?

2022-12-07 13:39 UTC, Kaes3kuch3n requested changes
Code Review ist schonmal erledigt, ausprobiert habe ich es noch nicht, schaffe ich aber hoffentlich im Laufe des Nachmittags :)
Eine wichtige Anmerkung (authMiddleware) ist dabei, die anderen sind nur Kleinigkeiten

2022-12-07 13:39 UTC, Kaes3kuch3n commented on client/src/components/admin/modals/EditCompanyModal.vue
> +      emailAddress: undefined as string | undefined,
Die Property wird nirgends benutzt 🤔Kann die weg?

2022-12-07 13:39 UTC, Kaes3kuch3n commented on client/src/components/internship/EditInternship.vue
> +            this.availablePaymentTypes.push(`${this.$t(st + pt.replace(/\s/g, ''))}`);
Das hier müsste denke ich kein Template String sein :)
```suggestion
            this.availablePaymentTypes.push(this.$t(st + pt.replace(/\s/g, '')));
```

2022-12-07 13:39 UTC, Kaes3kuch3n commented on server/src/controllers/company.ts
> +  // if (!user.isAdmin ) return next(new Forbidden("Only admins may edit companies"));
Nicht unbedingt, aber theoretisch könnte dann irgendein User alle Companies über einen direkten API-Call bearbeiten, ohne dass das irgendwie moderiert wird. Wenn wir das Risiko eingehen wollen, dann ist's kein Problem 😅

2022-12-07 13:39 UTC, Kaes3kuch3n commented on server/src/routes/company.ts
> +  // authMiddleware(true),
Die Middleware müsste drinnen bleiben, sonst kann man ohne Login ne Company bearbeiten. Aber das `true` kann zu einem `false` werden, damit das nicht nur Admins können.

2023-01-22 19:10 UTC, Kaes3kuch3n approved these changes

2023-01-22 19:10 UTC, merged