Added reasons functionality for pdf document rejections
imimap/imimap21 pull request #341
Opened 2023-04-21 21:22 UTC by Kaes3kuch3n

Closes #305 

Student View:
<img width="681" alt="Screenshot 2023-04-21 at 23 15 53" src="https://user-images.githubusercontent.com/8218240/233736474-a34da2b3-5c0b-4f06-95b6-538aa51adb18.png">

Admin View:
<img width="794" alt="Screenshot 2023-04-21 at 23 20 33" src="https://user-images.githubusercontent.com/8218240/233736649-f5f18f77-2e31-44dc-b9f6-8bec8ea7b0a0.png">
<img width="1152" alt="Screenshot 2023-04-21 at 23 21 04" src="https://user-images.githubusercontent.com/8218240/233736656-7f9c8575-89d0-4ccf-b37f-25a23dd5c944.png">

2023-05-07 09:15 UTC, JuliaZamaitat commented
@Kaes3kuch3n 
Richtig nice, gefällt mir sehr gut! Auch dein Refactoring an manchen Stellen :) 

Könntest du nur noch eine Sache hinzufügen bitte: und zwar, dass man nur PDFs hochladen kann, und keine anderen Dokumenttypen? Das macht uns die Arbeit im Nachhinein leichter.

Danke!

2023-05-07 09:16 UTC, JuliaZamaitat requested changes
@Kaes3kuch3n
Richtig nice, gefällt mir sehr gut! Auch dein Refactoring an manchen Stellen :)

Könntest du nur noch eine Sache hinzufügen bitte: und zwar, dass man nur PDFs hochladen kann, und keine anderen Dokumenttypen? Das macht uns die Arbeit im Nachhinein leichter.

Danke!

2023-05-17 06:25 UTC, StrippgenHTW commented
Hmm,
ich habe mal ge-merged, wie ich dachte. Nun heißt es
TS2305: Module '"@/utils/gateways"' has no exported member 'markInternshipAsForcePassed'.
..und soweit ich das sehe, stimmt das auch... ich denke das kann raus...
ich versuche das mal. Und baue auch gleich
accept=".pdf"
beim file input ein. Wish me luck!

2023-05-17 08:40 UTC, JuliaZamaitat approved these changes

2023-05-17 08:51 UTC, merged